### ISSUE TITLE
session recording

### ISSUE THREAD

**Issue by amircloner** [kaltura/adobe-connect-to-mkv-to-kaltura#20]
hi
this scrip can record adobe connect meet?
can recorrded chats, attendees and teacher notebook? this problem that other recording cannot record chats and links in abobe connect meet has been solve?

**Comment by jessp01** [comment]
Hello @amircloner ,

See https://github.com/kaltura/adobe-connect-to-mkv-to-kaltura#general-flow

Basically, the end result of running this code will be a video where you see exactly what you see while viewing the recording in a browser.
